version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_local
    ports:
      - "8080:8080"

    depends_on:
      - db
      - redis
      - mail
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/BooksManagement
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # メール送信方式
      MAIL_EXTERNAL_ENABLED: "true"
      MAILJET_API_KEY: "002898db257259df4509faf9b7752cb0"
      MAILJET_API_SECRET: "005cab1a33784797d74efb15ba89d3f4"
      MAIL_FROM_EMAIL: "system-sender@librolog.com"
      MAIL_FROM_NAME: "Libro Log"
      # Java エンコーディング設定
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -Dmail.mime.charset=UTF-8 -Dspring.messages.encoding=UTF-8"
      LANG: ja_JP.UTF-8

    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_local
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  db:
    build: ./mysql-config
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BooksManagement
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
  # - ./mysql-config/custom.cnf:/etc/mysql/conf.d/custom.cnf

  mail:
    # Web画面: http://localhost:19980
    image: axllent/mailpit:latest
    ports:
      - "19925:1025"
      - "19980:8025"
    volumes:
      - ./mailpit:/data
    environment:
      TZ: Asia/Tokyo
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      LANG: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
