name: Static Analysis for Java, JavaScript, and CSS

on:
  push:
    branches:
      # - main
      # - transferToReact
      - issues/#175-add-workflow-test
  pull_request:
    branches:
      # - main
      # - transferToReact
      - issues/#175-add-workflow-test

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Install dependencies
        run: |
          project-root/backend/mvnw install -DskipTests
          project-root/frontend/npm install

      - name: Run Checkstyle (Java)
        run: |
          ./mvnw checkstyle:check

      - name: Run SpotBugs (Java)
        run: |
          ./mvnw spotbugs:check

      - name: Run ESLint (JavaScript)
        run: |
          npx eslint . --ext .js,.jsx

      - name: Run Stylelint (CSS)
        run: |
          npx stylelint '**/*.css'
