name: Static Analysis for Java, JavaScript, and CSS

on:
  push:
    branches:
      # - main
      # - transferToReact
      - issues/#175-add-workflow-test
  pull_request:
    branches:
      # - main
      # - transferToReact
      - issues/#175-add-workflow-test

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: oracle

      - name: Install dependencies
        run: |
          cd project-root/backend
          ./mvnw install -DskipTests
          cd ../../project-root/frontend
          npm install

      - name: Run Checkstyle (Java)
        run: |
          cd project-root/backend
          ./mvnw checkstyle:check
        continue-on-error: true  # 失敗しても続行

      - name: Run SpotBugs (Java)
        run: |
          cd project-root/backend
          ./mvnw spotbugs:check
        continue-on-error: true  # 失敗しても続行

      - name: Run ESLint (JavaScript)
        run: |
          cd project-root/frontend
          npx eslint . --ext .js,.jsx
        continue-on-error: true  # 失敗しても続行

      - name: Run Stylelint (CSS)
        run: |
          cd project-root/frontend
          npx stylelint '**/*.css'
        continue-on-error: true  # 失敗しても続行
