steps:
  # Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'gcr.io/$PROJECT_ID/github.com/$_REPO_NAME/$SHORT_SHA', '.'
    ]

  # GCR へプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/$_REPO_NAME/$SHORT_SHA']

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'frontend-service',
        '--image', 'gcr.io/$PROJECT_ID/github.com/$_REPO_NAME/$SHORT_SHA',
        '--region', 'asia-northeast1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/github.com/$_REPO_NAME/$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY